current_sum = float(input())
current_sum = int(current_sum * 100)
coins_counter = 0
while current_sum > 0:
    if current_sum - 200 >= 0:
        current_sum -= 200
        coins_counter += 1
    elif current_sum - 100 >= 0:
        current_sum -= 100
        coins_counter += 1
    elif current_sum - 50 >= 0:
        current_sum -= 50
        coins_counter += 1
    elif current_sum - 20 >= 0:
        current_sum -= 20
        coins_counter += 1
    elif current_sum - 10 >= 0:
        current_sum -= 10
        coins_counter += 1
    elif current_sum - 5 >= 0:
        current_sum -= 5
        coins_counter += 1
    elif current_sum - 2 >= 0:
        current_sum -= 2
        coins_counter += 1
    elif current_sum - 1 >= 0:
        current_sum -= 1
        coins_counter += 1
print(coins_counter)